# Generated by Django 5.1.2 on 2024-11-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('id_colaborador', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspelhoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Selecione o arquivo PDF do espelho de ponto', upload_to='espelho_ponto/', verbose_name='Arquivo PDF')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
            ],
            options={
                'verbose_name': 'Espelho de Ponto',
                'verbose_name_plural': 'Espelhos de Ponto',
            },
        ),
    ]
