# Generated by Django 5.1.2 on 2024-11-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_colaborador_options_colaborador_data_admissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Espelho de Ponto', max_length=100, verbose_name='Nome do Site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_config/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_config/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Ex: #3B82F6', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#1D4ED8', help_text='Ex: #1D4ED8', max_length=7, verbose_name='Cor Secundária')),
                ('background_color', models.CharField(default='#F3F4F6', max_length=7, verbose_name='Cor de Fundo')),
                ('text_color', models.CharField(default='#111827', max_length=7, verbose_name='Cor do Texto')),
                ('link_color', models.CharField(default='#2563EB', max_length=7, verbose_name='Cor dos Links')),
                ('dark_background_color', models.CharField(default='#1F2937', max_length=7, verbose_name='Cor de Fundo (Modo Escuro)')),
                ('dark_text_color', models.CharField(default='#F9FAFB', max_length=7, verbose_name='Cor do Texto (Modo Escuro)')),
                ('dark_link_color', models.CharField(default='#60A5FA', max_length=7, verbose_name='Cor dos Links (Modo Escuro)')),
                ('welcome_text', models.CharField(default='Espelho de Ponto Digital', max_length=200, verbose_name='Texto de Boas-vindas')),
                ('welcome_subtitle', models.CharField(default='Acesse seu espelho de ponto de forma rápida e segura', max_length=200, verbose_name='Subtítulo de Boas-vindas')),
                ('footer_text', models.TextField(default='© {% now "Y" %} Espelho de Ponto Digital. Todos os direitos reservados.', verbose_name='Texto do Rodapé')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL do Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL do Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL do LinkedIn')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
