# Generated by Django 5.1.2 on 2024-12-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='equipe',
            field=models.CharField(default='MUSASHI', max_length=100, verbose_name='Equipe'),
        ),
    ]
