"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-temporary-key-for-build')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('PGDATABASE'),
        'USER': config('PGUSER'),
        'PASSWORD': config('PGPASSWORD'),
        'HOST': config('PGHOST'),
        'PORT': config('PGPORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de mídia para os arquivos PDF
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configurações de arquivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Remova ou comente as configurações do compressor
# COMPRESS_ENABLED = True
# COMPRESS_ROOT = STATIC_ROOT
# COMPRESS_OFFLINE = True
# ...

# Configurações do Jazzmin
JAZZMIN_SETTINGS = {
    # Título e cabeçalho
    "site_title": "Espelho de Ponto",
    "site_header": "Administração do Sistema",
    "site_brand": "Espelho de Ponto",
    "site_logo": None,  # Você pode adicionar um logo depois
    "welcome_sign": "Bem-vindo(a) ao Sistema",
    
    # Customização do Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Ícones do menu (usando FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "app.colaborador": "fas fa-users",
        "app.espelhoponto": "fas fa-file-alt",
        "app.siteconfiguration": "fas fa-cogs",
    },
    
    # Organização do Menu
    "order_with_respect_to": ["app", "auth"],
    
    # Itens do Menu
    "menu": [
        {
            "name": "Colaboradores",
            "url": "admin:app_colaborador_changelist",
            "icon": "fas fa-users",
        },
        {
            "name": "Espelhos de Ponto",
            "url": "admin:app_espelhoponto_changelist",
            "icon": "fas fa-file-alt",
        },
        {
            "name": "Configurações",
            "icon": "fas fa-cogs",
            "children": [
                {
                    "name": "Configuração do Site",
                    "url": "admin:app_siteconfiguration_changelist",
                    "icon": "fas fa-sliders-h",
                },
                {
                    "name": "Usuários",
                    "url": "admin:auth_user_changelist",
                    "icon": "fas fa-user",
                },
                {
                    "name": "Grupos",
                    "url": "admin:auth_group_changelist",
                    "icon": "fas fa-users-cog",
                },
            ]
        },
    ],
    
    # Customização do Dashboard
    "custom_css": "admin/css/custom_jazzmin.css",
    "custom_js": None,
    "show_ui_builder": True,
    
    # Cards do Dashboard
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    
    # Configurações do usuário atualizadas
    "usermenu_links": [
        {
            "name": "Meu Perfil",
            "url": "admin:auth_user_change",
            "icon": "fas fa-user-circle",
        },
        {
            "name": "Alterar Senha",
            "url": "admin:password_change",
            "icon": "fas fa-key",
        },
        {
            "name": "Sair",
            "url": "admin:logout",
            "icon": "fas fa-sign-out-alt",
        },
    ],
    
    # Customização do cabeçalho
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Suporte", "url": "#", "new_window": True},
        {"model": "auth.User"},
        {"app": "app"},
    ],
    
    # Customização do rodapé
    "show_footer": True,
    "copyright": "Espelho de Ponto Digital © 2024",
    "footer_links": [
        {"name": "Desenvolvido por Sua Empresa", "url": "https://suaempresa.com.br"},
        {"name": "Versão 1.0", "url": "#"},
        {"name": "Suporte", "url": "mailto:suporte@suaempresa.com.br"},
    ],
    # Adicione isso para mostrar o menu do usuário
    "show_sidebar": True,
    "show_ui_builder": True,
    "show_ui_builder_icon": True,
    "show_user_avatar": True,  # Mostra avatar do usuário
    "user_avatar_field": "get_avatar_url",  # Campo para o avatar (opcional)
    
    # Customização do cabeçalho com usuário
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Adicione suporte ao dark mode
    "dark_mode_theme": "darkly",
    "show_dark_mode_toggle": True,
    
    # Customização das cores para dark mode
    "dark_mode_colors": {
        "primary": "#3b82f6",
        "secondary": "#64748b",
        "success": "#22c55e",
        "info": "#0ea5e9",
        "warning": "#eab308",
        "danger": "#ef4444",
    },
}

# Customização das Cores do Tema
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    # Adicione suporte ao dark mode
    "dark_mode_theme": True,
    "theme": "default",
    "dark_theme": "darkly",
}

# Configuração para arquivos temporários
TEMP_PDFS_DIR = os.path.join(MEDIA_ROOT, 'temp_pdfs')
os.makedirs(TEMP_PDFS_DIR, exist_ok=True)

# Configurações de Autenticação
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configurações de Login
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = 'admin:index'
LOGOUT_REDIRECT_URL = 'admin:login'

# Configurações de Sessão
SESSION_COOKIE_AGE = 3600  # 1 hora em segundos
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    # adicione outros domínios conforme necessário
]

CORS_ALLOWED_ORIGINS = [
    'https://*.railway.app',
    # adicione outros domínios conforme necessário
]
