"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-temporary-key-for-build')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.site_configuration',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if config('ENVIRONMENT', default='development') == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('PGDATABASE'),
            'USER': config('PGUSER'),
            'PASSWORD': config('PGPASSWORD'),
            'HOST': config('PGHOST'),
            'PORT': config('PGPORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de mídia para os arquivos PDF
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configurações de arquivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Remova ou comente as configurações do compressor
# COMPRESS_ENABLED = True
# COMPRESS_ROOT = STATIC_ROOT
# COMPRESS_OFFLINE = True
# ...

# Configurações do Jazzmin
JAZZMIN_SETTINGS = {
    # Título e cabeçalho
    "site_title": "Espelho de Ponto",
    "site_header": "Administração do Sistema",
    "site_brand": "Espelho de Ponto",
    "site_logo": None,  # Você pode adicionar um logo depois
    "welcome_sign": "Bem-vindo(a) ao Sistema",
    
    # Customização do Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Ícones do menu (usando FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "app.colaborador": "fas fa-users",
        "app.espelhoponto": "fas fa-file-alt",
        "app.siteconfiguration": "fas fa-cogs",
    },
    
    # Organização do Menu
    "order_with_respect_to": ["app", "auth"],
    
    # Itens do Menu
    "menu": [
        {
            "name": "Colaboradores",
            "url": "admin:app_colaborador_changelist",
            "icon": "fas fa-users",
        },
        {
            "name": "Espelhos de Ponto",
            "url": "admin:app_espelhoponto_changelist",
            "icon": "fas fa-file-alt",
        },
        {
            "name": "Configurações",
            "icon": "fas fa-cogs",
            "children": [
                {
                    "name": "Configuração do Site",
                    "url": "admin:app_siteconfiguration_changelist",
                    "icon": "fas fa-sliders-h",
                },
                {
                    "name": "Usuários",
                    "url": "admin:auth_user_changelist",
                    "icon": "fas fa-user",
                },
                {
                    "name": "Grupos",
                    "url": "admin:auth_group_changelist",
                    "icon": "fas fa-users-cog",
                },
            ]
        },
    ],
    
    # Customização do Dashboard
    "custom_css": "admin/css/custom_jazzmin.css",
    "custom_js": None,
    "show_ui_builder": False,
    
    # Cards do Dashboard
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    
    # Configurações do usuário
    "usermenu_links": [
        {
            "name": "Meu Perfil",
            "url": "admin:auth_user_change",
            "icon": "fas fa-user-circle",
        },
        {
            "name": "Alterar Senha",
            "url": "admin:password_change",
            "icon": "fas fa-key",
        },
        {
            "name": "Sair",
            "url": "admin:logout",
            "icon": "fas fa-sign-out-alt",
        },
    ],
    
    # Customização do cabeçalho
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Suporte", "url": "#", "new_window": True},
        {"model": "auth.User"},
        {"app": "app"},
    ],
    
    # Customização do rodapé
    "show_footer": True,
    "copyright": "Espelho de Ponto Digital © 2024",
    "footer_links": [
        {
            "name": "Desenvolvido por Johnathan Herbert", 
            "url": "https://github.com/johnathanherbert",
            "new_window": True
        },
        {"name": "Versão 1.0", "url": "#"},
        {"name": "Suporte", "url": "mailto:johnathan.herbert47@gmail.com"},
    ],
    
    # Configurações de UI
    "show_sidebar": True,
    "show_ui_builder": False,
    "show_ui_builder_icon": False,
    "show_user_avatar": True,
    "user_avatar_field": "get_avatar_url",
    
    # Customização do cabeçalho com usuário
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Forçar tema claro
    "theme": "default",
    "dark_mode_theme": None,
}

# Customização das Cores do Tema
JAZZMIN_UI_TWEAKS = {
    # Cores claras específicas
    "navbar": "navbar-light",
    "sidebar": "sidebar-light-primary",
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    # Cores personalizadas
    "theme": "light",
    "dark_mode_theme": None,
    "custom_css": "admin/css/custom.css",  # CSS personalizado
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
}

# Configuração para arquivos temporários
TEMP_PDFS_DIR = os.path.join(MEDIA_ROOT, 'temp_pdfs')
os.makedirs(TEMP_PDFS_DIR, exist_ok=True)

# Configurações de Autenticação
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configurações de Login
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = 'admin:index'
LOGOUT_REDIRECT_URL = 'admin:login'

# Configurações de Sessão
SESSION_COOKIE_AGE = 3600  # 1 hora em segundos
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'http://127.0.0.1:8000',
    # seu domínio aqui
]

CORS_ALLOWED_ORIGINS = [
    'https://*.railway.app',
    # adicione outros domínios conforme necessário
]

# Configuração de arquivos estáticos e mídia
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Habilitar compressão e caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configurar WhiteNoise para servir arquivos de mídia também
WHITENOISE_ROOT = MEDIA_ROOT

# Configurações de segurança para PDFs
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_CONTENT_TYPE_NOSNIFF = True
